version: '3.7'
services:
  collector:
    build:
      context: collector
    env_file: collector/.env
    volumes:
      - ./collector:/app/src
      - ./data:/app/data
  server:
    build:
      context: server
    env_file: server/.env
    environment:
      APPLICATION_ARG: '--debug --host 0.0.0.0'
      NEOTTER_SERVER_PORT: 8080
    depends_on:
      - collector
    volumes:
      - ./server:/app/src
      - ./data:/app/data
    ports:
        - 8080:80
