version: '3.7'
services:
  collector:
    image: tuttuvr/message-collector:${TAG}
    build:
      context: collector
  server:
    image: tuttuvr/message-api:${TAG}
    build:
      context: server
    depends_on:
      - collector
    ports:
        - 80:80
