version: '3.7'
services:
  collector:
    image: tuttuvr/message-collector:${TAG}
    build:
      context: collector
    env_file: collector/.env
    volumes:
      - /var/db/neos-twitter:/app/data
  server:
    image: tuttuvr/message-api:${TAG}
    build:
      context: server
    environment:
      APPLICATION_ARG: '--host 0.0.0.0'
    depends_on:
      - collector
    ports:
      - 80:80
    volumes:
      - /var/db/neos-twitter:/app/data
    environment:
      - NEOTTER_HOST_NAME=tuttuvr.work
