version: '3.7'
services:
  collector:
    build:
      context: collector
    env_file: collector/.env
    volumes:
      - ./collector:/app/src
      - ./data:/app/data
  server:
    build:
      context: server
      args:
        application_arg: "--debug"
    env_file: server/.env
    depends_on:
      - collector
    volumes:
      - ./server:/app/src
      - ./data:/app/data
    ports:
        - 80:80
