version: '3.7'
services:
  collector:
    image: tuttuvr/message-collector:${TAG}
    build:
      context: collector
    env_file: collector/.env
    volumes:
      - /var/db/neos-twitter:/app/data
  server:
    image: tuttuvr/message-api:${TAG}
    build:
      context: server
    env_file: server/.env
    environment:
      APPLICATION_ARG: '--host 0.0.0.0'
      APPLICATION_ENV: production
      NEOTTER_HOST_NAME: tuttuvr.work
      NEOTTER_PROTO: https
    depends_on:
      - collector
    ports:
      - 8080:80
    volumes:
      - /var/db/neos-twitter:/app/data
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
