name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.run_id }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: |
        mv docker-compose-prod.yml docker-compose.yml
        touch collector/.env
        build.sh
    - name: Push the Docker images
      if: github.event_name == 'push'
      run: |
        docker login --username="${{ secrets.DOCKER_HUB_NAME }}" --password="${{ secrets.DOCKER_HUB_PASS }}"
        docker-compose push
        TAG=latest docker-compose build
        TAG=latest docker-compose push
