name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.ref }}-${{ github.run_id }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: |
        docker login --username="${{ secrets.DOCKER_HUB_NAME }}" --password="${{ secrets.DOCKER_HUB_PASS }}"
        mv docker-compose-prod.yml docker-compose.yml
        docker-compose build
    - name: Push the Docker images
      if: ${{ github.ref == 'master' }}
      run: docker-compose push
