name: Python Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd test
        ./init.sh
    - name: Test
      run: |
        cd test
        find collector -name 'test_*.py' | xargs python -m unittest
        find server -name 'test_*.py' | xargs python -m unittest
